from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class PlaneStatus(str, Enum):
    IDLE = "idle"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class GoalClassification(str, Enum):
    SIMPLE = "simple"
    COMPLEX = "complex"
    ADVERSARIAL = "adversarial"
    NOVEL = "novel"


class CognitivePhase(str, Enum):
    ANALYZE = "analyze"
    PLAN = "plan"
    EXECUTE = "execute"
    VERIFY = "verify"
    REPORT = "report"


@dataclass
class PlaneState:
    """State tracking for an individual cognitive plane."""
    plane_id: str
    status: PlaneStatus = PlaneStatus.IDLE
    output: dict[str, Any] = field(default_factory=dict)
    error: str | None = None
    started_at: float | None = None
    completed_at: float | None = None

    def mark_running(self) -> None:
        self.status = PlaneStatus.RUNNING
        self.started_at = time.time()
        self.error = None

    def mark_completed(self, output: dict[str, Any] | None = None) -> None:
        self.status = PlaneStatus.COMPLETED
        self.completed_at = time.time()
        if output is not None:
            self.output = output

    def mark_failed(self, error: str) -> None:
        self.status = PlaneStatus.FAILED
        self.completed_at = time.time()
        self.error = error

    def mark_skipped(self, reason: str | None = None) -> None:
        self.status = PlaneStatus.SKIPPED
        self.completed_at = time.time()
        if reason:
            self.output = {"skipped_reason": reason}

    def to_dict(self) -> dict[str, Any]:
        return {
            "plane_id": self.plane_id,
            "status": self.status.value,
            "output": self.output,
            "error": self.error,
            "started_at": self.started_at,
            "completed_at": self.completed_at,
        }


@dataclass
class EvidenceItem:
    """Discrete, typed evidence item generated by a cognitive plane."""
    evidence_id: str = field(default_factory=lambda: f"evi_{uuid.uuid4().hex[:10]}")
    plane_id: str = ""
    evidence_type: str = ""
    content: dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0  # 0.0 to 1.0
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> dict[str, Any]:
        return {
            "evidence_id": self.evidence_id,
            "plane_id": self.plane_id,
            "evidence_type": self.evidence_type,
            "content": self.content,
            "confidence": self.confidence,
            "timestamp": self.timestamp,
        }


@dataclass
class BlackboardSnapshot:
    """Serializable snapshot of the full multi-plane blackboard working memory."""
    session_id: str
    goal: str
    goal_classification: str
    current_phase: str
    plane_states: dict[str, dict[str, Any]]
    shared_context: dict[str, Any]
    evidence_trail: list[dict[str, Any]]
    created_at: float
    updated_at: float

    def to_dict(self) -> dict[str, Any]:
        return {
            "session_id": self.session_id,
            "goal": self.goal,
            "goal_classification": self.goal_classification,
            "current_phase": self.current_phase,
            "plane_states": self.plane_states,
            "shared_context": self.shared_context,
            "evidence_trail": self.evidence_trail,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }
