import json
from pathlib import Path
import pytest
from deerflow.learning.curator import LearningGraphCurator
from deerflow.learning.graph import KnowledgeGraph, KnowledgeNode
from deerflow.learning.store import LearningGraphStore
from deerflow.tools.builtins.learning_graph_tool import learning_graph_manage


def test_knowledge_graph_basics_and_stats():
    graph = KnowledgeGraph()
    n1 = KnowledgeNode(title="FastAPI Lifespan Setup", content="Use asynccontextmanager for lifespan events in FastAPI", category="api")
    n2 = KnowledgeNode(title="FastAPI Test Client", content="Use TestClient or AsyncClient with lifespan for testing FastAPI endpoints", category="testing")
    n3 = KnowledgeNode(title="Postgres Indexing", content="Add B-Tree indexes on foreign keys", category="db")

    graph.add_node(n1)
    graph.add_node(n2)
    graph.add_node(n3)

    # Auto link based on FastAPI lexical overlap
    new_edges = graph.auto_link_lexical(threshold=0.15)
    assert new_edges >= 1

    stats = graph.density_stats()
    assert stats["total_nodes"] == 3
    assert stats["total_edges"] >= 1
    assert stats["categories_count"] == 3

    # Query
    matches = graph.query("FastAPI endpoints", category="testing")
    assert len(matches) == 1
    assert matches[0].title == "FastAPI Test Client"


def test_curator_prune_and_merge():
    graph = KnowledgeGraph()
    # Stale unpinned node
    stale = KnowledgeNode(title="Old Temp Rule", content="temp rule", category="tmp", timestamp=1000.0, use_count=0, pinned=False)
    # Stale pinned node
    pinned = KnowledgeNode(title="Pinned Core Invariant", content="core rule", category="core", timestamp=1000.0, use_count=0, pinned=True)
    # Duplicate nodes
    d1 = KnowledgeNode(title="Git Commit Guideline", content="Always format commit messages in conventional commits", category="git")
    d2 = KnowledgeNode(title="Git Commit Guideline", content="Always format commit messages in conventional commits format", category="git")

    graph.add_node(stale)
    graph.add_node(pinned)
    graph.add_node(d1)
    graph.add_node(d2)

    curator = LearningGraphCurator()
    # Prune stale
    pruned = curator.prune_decayed(graph, max_age_seconds=100.0)
    assert pruned == 1
    assert stale.node_id not in graph.nodes
    assert pinned.node_id in graph.nodes  # Pinned survived

    # Merge duplicates
    merged = curator.merge_duplicates(graph, similarity_threshold=0.80)
    assert merged >= 1
    assert len([n for n in graph.nodes.values() if "Git Commit" in n.title]) == 1


def test_learning_graph_manage_tool(tmp_path: Path, monkeypatch):
    store = LearningGraphStore(root_dir=tmp_path)
    monkeypatch.setattr("deerflow.learning.store.get_learning_graph_store", lambda: store)
    monkeypatch.setattr("deerflow.tools.builtins.learning_graph_tool.get_learning_graph_store", lambda: store)

    # Record
    rec_res = learning_graph_manage.invoke({
        "action": "record",
        "title": "Alembic Migrations",
        "text": "Always verify autogenerated Alembic revisions before applying",
        "category": "database",
        "pinned": True,
    })
    assert "Recorded knowledge node" in rec_res

    # Query
    q_res = learning_graph_manage.invoke({"action": "query", "text": "Alembic autogenerated"})
    assert "Alembic Migrations" in q_res

    # Stats
    stats_res = learning_graph_manage.invoke({"action": "stats"})
    parsed = json.loads(stats_res)
    assert parsed["total_nodes"] == 1
