"""Gateway security-headers middleware.

Adds baseline HTTP response hardening headers to every Gateway response,
including auth/CSRF rejections and the trace fallback 500.

Placement: registered LAST in ``create_app()`` so it is the outermost user
middleware (Starlette's ``add_middleware`` prepends and the stack is built
inside-out, so the last-registered middleware runs first on the way in and
last on the way out). Outermost placement is what lets rejection responses
generated by inner layers (``AuthMiddleware`` 401s, ``CSRFMiddleware`` 403s)
pass through this wrapper on their way out.

Pure-ASGI style (like ``TraceMiddleware``): headers are attached at
``http.response.start`` so streaming/SSE responses are covered without
consuming the body. Existing values are never overwritten, so an inner layer
or route can still tighten a header for its own responses.

``Strict-Transport-Security`` is sent only when the request arrived over
HTTPS (direct ``scope["scheme"]`` or ``X-Forwarded-Proto: https`` from the
terminating proxy, which the bundled nginx sets). Local plain-HTTP
deployments never receive it, so browsers are never pinned to HTTPS for a
host that does not serve it.

``Permissions-Policy`` deliberately leaves ``microphone`` at its default:
the frontend voice-input uses browser speech recognition, which needs a
microphone grant. Only ``camera`` and ``geolocation`` are disabled, which no
DeerFlow surface uses.
"""

from __future__ import annotations

from starlette.datastructures import Headers, MutableHeaders
from starlette.types import ASGIApp, Message, Receive, Scope, Send

_HSTS_VALUE = "max-age=31536000; includeSubDomains"

_STATIC_HEADERS: tuple[tuple[str, str], ...] = (
    ("x-content-type-options", "nosniff"),
    ("referrer-policy", "same-origin"),
    ("x-frame-options", "SAMEORIGIN"),
    # microphone intentionally omitted: frontend voice-input needs the grant.
    ("permissions-policy", "camera=(), geolocation=()"),
)


def _request_is_https(scope: Scope) -> bool:
    """Return True when the client-facing request arrived over HTTPS."""
    if scope.get("scheme") == "https":
        return True
    forwarded_proto = Headers(scope=scope).get("x-forwarded-proto", "")
    return forwarded_proto.split(",")[0].strip().lower() == "https"


class SecurityHeadersMiddleware:
    """Attach baseline security headers to every HTTP response."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        https = _request_is_https(scope)

        async def send_with_headers(message: Message) -> None:
            if message["type"] == "http.response.start":
                headers = MutableHeaders(scope=message)
                for name, value in _STATIC_HEADERS:
                    if name not in headers:
                        headers[name] = value
                if https and "strict-transport-security" not in headers:
                    headers["strict-transport-security"] = _HSTS_VALUE
            await send(message)

        await self.app(scope, receive, send_with_headers)
