from __future__ import annotations
from .registry import CommandCategory


def get_default_catalog_entries():
    entries = [
        # 1. Core / Help
        ("/help", CommandCategory.CORE, "Shows available commands, syntax, examples and permissions", "/help [category]", True),
        ("/commands", CommandCategory.CORE, "Opens the complete command catalog", "/commands [search|categories]", True),
        ("/commands search", CommandCategory.CORE, "Finds commands by capability", "/commands search <query>", False),
        ("/commands categories", CommandCategory.CORE, "Shows commands grouped into functional categories", "/commands categories", False),
        ("/version", CommandCategory.CORE, "Shows SI version, runtime, build and environment information", "/version", False),
        ("/about", CommandCategory.CORE, "Shows project/runtime information and capabilities", "/about", False),
        ("/status", CommandCategory.CORE, "Shows current mission, agents, model, tools, tokens and runtime state", "/status", True),
        ("/doctor", CommandCategory.CORE, "Diagnoses broken models, tools, MCP, sandbox, network and configuration", "/doctor", True),
        ("/diagnostics", CommandCategory.CORE, "Produces a detailed diagnostic report for troubleshooting", "/diagnostics", False),
        ("/whoami", CommandCategory.CORE, "Shows current user identity, role and permission level", "/whoami", False),
        ("/capabilities", CommandCategory.CORE, "Shows what the current agent/runtime is capable of doing", "/capabilities", True),
        ("/tools", CommandCategory.CORE, "Shows currently available tools and their status", "/tools", True),
        ("/skills", CommandCategory.CORE, "Shows installed, available and active skills", "/skills", True),
        # 2. Mission / Goal Commands
        ("/goal", CommandCategory.MISSION, "Shows the current mission and its state", "/goal", True),
        ("/goal create", CommandCategory.MISSION, "Creates a durable autonomous mission", "/goal create <objective>", True, True),
        ("/goal start", CommandCategory.MISSION, "Starts execution of current mission", "/goal start", False),
        ("/goal pause", CommandCategory.MISSION, "Temporarily pauses mission execution without losing state", "/goal pause", True),
        ("/goal resume", CommandCategory.MISSION, "Resumes a paused mission from checkpoint", "/goal resume", True),
        ("/goal edit", CommandCategory.MISSION, "Changes objective, constraints or requirements", "/goal edit <text>", False),
        ("/goal status", CommandCategory.MISSION, "Shows completion percentage, blockers, subtasks and risks", "/goal status", True),
        ("/goal complete", CommandCategory.MISSION, "Marks goal complete after verification", "/goal complete", False),
        ("/goal cancel", CommandCategory.MISSION, "Safely terminates current mission", "/goal cancel", False),
        ("/goal block", CommandCategory.MISSION, "Marks goal as blocked and records reason", "/goal block <reason>", False),
        ("/goal clear", CommandCategory.MISSION, "Removes active mission from session", "/goal clear", False),
        ("/goal verify", CommandCategory.MISSION, "Runs goal-satisfaction evaluator before declaring success", "/goal verify", True),
        ("/goal expand", CommandCategory.MISSION, "Expands vague objective into measurable requirements", "/goal expand", False),
        ("/goal refine", CommandCategory.MISSION, "Improves an existing goal specification", "/goal refine", False),
        ("/goal decompose", CommandCategory.MISSION, "Breaks mission into executable subgoals", "/goal decompose", True),
        ("/goal prioritize", CommandCategory.MISSION, "Reorders goals based on impact and dependency", "/goal prioritize", False),
        ("/goal constraints", CommandCategory.MISSION, "Shows or edits hard/soft mission constraints", "/goal constraints", False),
        ("/goal budget", CommandCategory.MISSION, "Shows or modifies mission resource limits", "/goal budget", False),
        # 3. Planning Commands
        ("/plan", CommandCategory.PLANNING, "Creates execution plan without immediately acting", "/plan <objective>", True),
        ("/plan show", CommandCategory.PLANNING, "Displays current execution plan", "/plan show", False),
        ("/plan approve", CommandCategory.PLANNING, "Approves generated plan for execution", "/plan approve", False),
        ("/plan reject", CommandCategory.PLANNING, "Rejects proposed plan", "/plan reject", False),
        ("/plan revise", CommandCategory.PLANNING, "Replans after feedback or new information", "/plan revise <feedback>", False),
        ("/plan deep", CommandCategory.PLANNING, "Performs deep architectural investigation before planning", "/plan deep <topic>", True, True),
        ("/plan compare", CommandCategory.PLANNING, "Generates multiple competing plans and compares them", "/plan compare <objective>", True),
        ("/plan optimize", CommandCategory.PLANNING, "Optimizes plan for cost, speed or quality", "/plan optimize", True),
        ("/plan parallelize", CommandCategory.PLANNING, "Finds tasks that can safely execute simultaneously", "/plan parallelize", True),
        ("/plan dependencies", CommandCategory.PLANNING, "Displays task dependency DAG", "/plan dependencies", False),
        ("/plan risk", CommandCategory.PLANNING, "Performs plan-level risk analysis", "/plan risk", False),
        ("/plan simulate", CommandCategory.PLANNING, "Simulates expected execution before acting", "/plan simulate", True),
        ("/plan explain", CommandCategory.PLANNING, "Explains why selected strategy was chosen", "/plan explain", False),
        ("/plan alternative", CommandCategory.PLANNING, "Generates alternative strategies", "/plan alternative", False),
        ("/plan freeze", CommandCategory.PLANNING, "Prevents automatic plan changes temporarily", "/plan freeze", False),
        ("/plan unfreeze", CommandCategory.PLANNING, "Re-enables adaptive replanning", "/plan unfreeze", False),
        # 4. Execution Commands
        ("/run", CommandCategory.EXECUTION, "Executes current approved plan", "/run", True),
        ("/run auto", CommandCategory.EXECUTION, "Lets executive choose execution strategy", "/run auto", False),
        ("/run safe", CommandCategory.EXECUTION, "Runs with conservative permissions and approvals", "/run safe", False),
        ("/run autonomous", CommandCategory.EXECUTION, "Enables unattended execution within policy limits", "/run autonomous", True, True),
        ("/run parallel", CommandCategory.EXECUTION, "Executes independent tasks concurrently", "/run parallel", False),
        ("/run sequential", CommandCategory.EXECUTION, "Forces ordered task execution", "/run sequential", False),
        ("/run dry", CommandCategory.EXECUTION, "Simulates actions without performing side effects", "/run dry", True),
        ("/run resume", CommandCategory.EXECUTION, "Resumes interrupted execution", "/run resume", False),
        ("/run retry", CommandCategory.EXECUTION, "Retries failed execution", "/run retry", False),
        ("/run force", CommandCategory.EXECUTION, "Forces execution despite non-critical warnings", "/run force", False),
        ("/run cancel", CommandCategory.EXECUTION, "Cancels current execution", "/run cancel", False),
        ("/run inspect", CommandCategory.EXECUTION, "Shows planned actions before execution", "/run inspect", False),
        ("/run verify", CommandCategory.EXECUTION, "Executes then automatically verifies result", "/run verify", False),
        # 5. Swarm Commands
        ("/swarm", CommandCategory.SWARM, "Creates an automatically designed agent swarm", "/swarm [goal]", True, True),
        ("/swarm start", CommandCategory.SWARM, "Starts selected swarm", "/swarm start", False),
        ("/swarm stop", CommandCategory.SWARM, "Stops active swarm", "/swarm stop", False),
        ("/swarm pause", CommandCategory.SWARM, "Pauses all swarm workers while preserving state", "/swarm pause", False),
        ("/swarm resume", CommandCategory.SWARM, "Resumes swarm execution", "/swarm resume", False),
        ("/swarm status", CommandCategory.SWARM, "Shows live agents, tasks, costs and progress", "/swarm status", True),
        ("/swarm inspect", CommandCategory.SWARM, "Shows topology, roles and communication graph", "/swarm inspect", True),
        ("/swarm design", CommandCategory.SWARM, "Lets executive design optimal swarm topology", "/swarm design <objective>", True),
        ("/swarm optimize", CommandCategory.SWARM, "Optimizes agent count, topology and resource usage", "/swarm optimize", True),
        ("/swarm scale", CommandCategory.SWARM, "Dynamically increases/decreases workers", "/swarm scale <count>", False),
        ("/swarm parallel", CommandCategory.SWARM, "Creates parallel worker swarm", "/swarm parallel <tasks>", False),
        ("/swarm debate", CommandCategory.SWARM, "Creates competing agents that debate a problem", "/swarm debate <topic>", False),
        ("/swarm compete", CommandCategory.SWARM, "Generates competing solutions and selects winner", "/swarm compete <problem>", True),
        ("/swarm consensus", CommandCategory.SWARM, "Forces agents to reach evidence-based consensus", "/swarm consensus <decision>", False),
        ("/swarm hierarchy", CommandCategory.SWARM, "Creates manager -> worker hierarchy", "/swarm hierarchy", False),
        ("/swarm pipeline", CommandCategory.SWARM, "Creates sequential specialist stages", "/swarm pipeline", False),
        ("/swarm mapreduce", CommandCategory.SWARM, "Maps many workers then aggregates results", "/swarm mapreduce", False),
        ("/swarm research", CommandCategory.SWARM, "Automatically builds research swarm", "/swarm research <topic>", False),
        ("/swarm coding", CommandCategory.SWARM, "Creates engineering swarm", "/swarm coding <feature>", False),
        ("/swarm review", CommandCategory.SWARM, "Creates independent review swarm", "/swarm review", False),
        ("/swarm kill", CommandCategory.SWARM, "Terminates one swarm worker", "/swarm kill <agent_id>", False),
        ("/swarm rebalance", CommandCategory.SWARM, "Moves tasks between agents dynamically", "/swarm rebalance", False),
        ("/swarm merge", CommandCategory.SWARM, "Combines worker outputs into unified result", "/swarm merge", False),
        ("/swarm topology", CommandCategory.SWARM, "Displays current swarm topology", "/swarm topology", False),
        # 6. Agent Commands
        ("/agent", CommandCategory.AGENT, "Displays current agent information", "/agent [id]", True),
        ("/agent spawn", CommandCategory.AGENT, "Creates temporary specialist agent", "/agent spawn <role>", True),
        ("/agent create", CommandCategory.AGENT, "Creates reusable agent profile", "/agent create <name>", False),
        ("/agent list", CommandCategory.AGENT, "Lists available agents", "/agent list", False),
        ("/agent inspect", CommandCategory.AGENT, "Shows agent model, tools, skills and permissions", "/agent inspect <id>", True),
        ("/agent pause", CommandCategory.AGENT, "Pauses an agent", "/agent pause <id>", False),
        ("/agent resume", CommandCategory.AGENT, "Resumes an agent", "/agent resume <id>", False),
        ("/agent stop", CommandCategory.AGENT, "Terminates an agent", "/agent stop <id>", False),
        ("/agent restart", CommandCategory.AGENT, "Restarts agent from checkpoint", "/agent restart <id>", False),
        ("/agent delegate", CommandCategory.AGENT, "Delegates task to specialist", "/agent delegate <agent> <task>", True),
        ("/agent recruit", CommandCategory.AGENT, "Finds best available agent for capability", "/agent recruit <capability>", True),
        ("/agent replace", CommandCategory.AGENT, "Replaces failing/slow worker", "/agent replace <id>", False),
        ("/agent clone", CommandCategory.AGENT, "Creates copy of agent configuration", "/agent clone <id>", False),
        ("/agent specialize", CommandCategory.AGENT, "Creates specialist from generic agent", "/agent specialize <id> <domain>", False),
        ("/agent evaluate", CommandCategory.AGENT, "Benchmarks an agent on task", "/agent evaluate <id>", False),
        ("/agent benchmark", CommandCategory.AGENT, "Runs standardized capability tests", "/agent benchmark <id>", False),
        ("/agent reputation", CommandCategory.AGENT, "Shows historical agent performance", "/agent reputation <id>", False),
        ("/agent communicate", CommandCategory.AGENT, "Sends message to another agent", "/agent communicate <id> <msg>", False),
        ("/agent ask", CommandCategory.AGENT, "Queries another agent without delegating full work", "/agent ask <id> <question>", False),
        ("/agent tree", CommandCategory.AGENT, "Displays parent/child agent hierarchy", "/agent tree", True),
        # 7. Background Commands
        ("/bg", CommandCategory.BACKGROUND, "Runs task in separate background session", "/bg <task>", True),
        ("/tasks", CommandCategory.BACKGROUND, "Lists active and completed background jobs", "/tasks", True),
        ("/task", CommandCategory.BACKGROUND, "Displays specific background task", "/task <id>", False),
        ("/task pause", CommandCategory.BACKGROUND, "Pauses background job", "/task pause <id>", False),
        ("/task resume", CommandCategory.BACKGROUND, "Resumes background job", "/task resume <id>", False),
        ("/task cancel", CommandCategory.BACKGROUND, "Terminates background job", "/task cancel <id>", False),
        ("/task retry", CommandCategory.BACKGROUND, "Retries failed background task", "/task retry <id>", False),
        ("/task logs", CommandCategory.BACKGROUND, "Shows execution logs", "/task logs <id>", False),
        ("/task result", CommandCategory.BACKGROUND, "Displays final artifact/result", "/task result <id>", False),
        ("/task fork", CommandCategory.BACKGROUND, "Creates new task from existing state", "/task fork <id>", False),
        # 8. Research Commands
        ("/research", CommandCategory.RESEARCH, "Starts autonomous deep research", "/research <topic>", True),
        ("/research deep", CommandCategory.RESEARCH, "Uses multiple researchers and verification passes", "/research deep <topic>", True),
        ("/research quick", CommandCategory.RESEARCH, "Performs lightweight research", "/research quick <topic>", False),
        ("/research sources", CommandCategory.RESEARCH, "Shows sources discovered during research", "/research sources", False),
        ("/research verify", CommandCategory.RESEARCH, "Independently verifies research claims", "/research verify", True),
        ("/research counter", CommandCategory.RESEARCH, "Searches specifically for contradictory evidence", "/research counter <claim>", True),
        ("/research compare", CommandCategory.RESEARCH, "Compares competing technologies or claims", "/research compare <A> <B>", False),
        ("/research timeline", CommandCategory.RESEARCH, "Builds chronological research timeline", "/research timeline <topic>", False),
        ("/research map", CommandCategory.RESEARCH, "Creates evidence/knowledge map", "/research map", False),
        ("/research claims", CommandCategory.RESEARCH, "Lists claims and supporting evidence", "/research claims", False),
        ("/research gaps", CommandCategory.RESEARCH, "Finds unanswered questions and missing evidence", "/research gaps", True),
        ("/research synthesize", CommandCategory.RESEARCH, "Produces final evidence-backed synthesis", "/research synthesize", False),
        ("/research sourcescore", CommandCategory.RESEARCH, "Scores source credibility", "/research sourcescore", False),
        ("/research citations", CommandCategory.RESEARCH, "Validates citations and source relationships", "/research citations", False),
        ("/research exhaustive", CommandCategory.RESEARCH, "Searches until predefined coverage satisfied", "/research exhaustive <query>", False),
        ("/research frontier", CommandCategory.RESEARCH, "Searches specifically for newest developments", "/research frontier <field>", False),
        # 9. Memory Commands
        ("/memory", CommandCategory.MEMORY, "Shows memory subsystem status", "/memory", True),
        ("/memory search", CommandCategory.MEMORY, "Searches persistent memory", "/memory search <query>", True),
        ("/memory add", CommandCategory.MEMORY, "Adds explicit memory", "/memory add <content>", False),
        ("/memory forget", CommandCategory.MEMORY, "Requests removal/avoidance of memory", "/memory forget <query>", False),
        ("/memory inspect", CommandCategory.MEMORY, "Shows memory records and metadata", "/memory inspect", False),
        ("/memory summarize", CommandCategory.MEMORY, "Compresses memories into higher-level knowledge", "/memory summarize", False),
        ("/memory consolidate", CommandCategory.MEMORY, "Merges duplicate/related memories", "/memory consolidate", True),
        ("/memory repair", CommandCategory.MEMORY, "Detects and repairs inconsistent memories", "/memory repair", False),
        ("/memory promote", CommandCategory.MEMORY, "Promotes session knowledge to long-term memory", "/memory promote <key>", False),
        ("/memory demote", CommandCategory.MEMORY, "Moves low-value persistent memory down a tier", "/memory demote <key>", False),
        ("/memory prune", CommandCategory.MEMORY, "Removes stale memory according to policy", "/memory prune", False),
        ("/memory project", CommandCategory.MEMORY, "Shows project-specific memory", "/memory project", False),
        ("/memory user", CommandCategory.MEMORY, "Shows user-profile memory", "/memory user", False),
        ("/memory experience", CommandCategory.MEMORY, "Searches previous successful trajectories", "/memory experience <query>", False),
        ("/memory failure", CommandCategory.MEMORY, "Searches historical failures and recovery strategies", "/memory failure <query>", False),
        # 10. Context Commands
        ("/context", CommandCategory.CONTEXT, "Shows current context composition and usage", "/context", True),
        ("/context map", CommandCategory.CONTEXT, "Displays how context is assembled", "/context map", False),
        ("/context detail", CommandCategory.CONTEXT, "Shows token usage by memory/tool/history", "/context detail", False),
        ("/context optimize", CommandCategory.CONTEXT, "Automatically optimizes context for next step", "/context optimize", True),
        ("/context compact", CommandCategory.CONTEXT, "Compresses conversation history", "/context compact", False),
        ("/context prune", CommandCategory.CONTEXT, "Removes irrelevant context", "/context prune", False),
        ("/context preserve", CommandCategory.CONTEXT, "Protects critical information from compression", "/context preserve <item>", False),
        ("/context focus", CommandCategory.CONTEXT, "Rebuilds context around one topic", "/context focus <topic>", False),
        ("/context reset", CommandCategory.CONTEXT, "Clears active conversation context", "/context reset", False),
        ("/context export", CommandCategory.CONTEXT, "Exports current context snapshot", "/context export", False),
        ("/context restore", CommandCategory.CONTEXT, "Restores saved context snapshot", "/context restore", False),
        # 11. Skills Commands
        ("/skill", CommandCategory.SKILLS, "Invokes a specific skill", "/skill <name>", True),
        ("/skills search", CommandCategory.SKILLS, "Finds relevant skills", "/skills search <query>", False),
        ("/skills install", CommandCategory.SKILLS, "Installs a skill", "/skills install <name>", False),
        ("/skills uninstall", CommandCategory.SKILLS, "Removes a skill", "/skills uninstall <name>", False),
        ("/skills enable", CommandCategory.SKILLS, "Enables a skill", "/skills enable <name>", False),
        ("/skills disable", CommandCategory.SKILLS, "Disables a skill", "/skills disable <name>", False),
        ("/skills inspect", CommandCategory.SKILLS, "Shows skill manifest and instructions", "/skills inspect <name>", False),
        ("/skills test", CommandCategory.SKILLS, "Tests a skill against its benchmark", "/skills test <name>", False),
        ("/skills benchmark", CommandCategory.SKILLS, "Measures skill quality/performance", "/skills benchmark <name>", False),
        ("/skills create", CommandCategory.SKILLS, "Creates a new skill", "/skills create <name>", True),
        ("/skills improve", CommandCategory.SKILLS, "Generates an improved skill candidate", "/skills improve <name>", True),
        ("/skills audit", CommandCategory.SKILLS, "Audits installed skills for safety/quality", "/skills audit", False),
        ("/skills update", CommandCategory.SKILLS, "Updates skills", "/skills update", False),
        ("/skills rollback", CommandCategory.SKILLS, "Reverts a skill version", "/skills rollback <name>", False),
        ("/skills propose", CommandCategory.SKILLS, "Generates a skill proposal from repeated work", "/skills propose", False),
        ("/skills approve", CommandCategory.SKILLS, "Approves a generated skill", "/skills approve <name>", False),
        ("/learn", CommandCategory.SKILLS, "Turns a source into a reusable skill draft", "/learn <source>", True),
        ("/moa", CommandCategory.MODEL, "Multi-advisor turn: gather drafts, then synthesize", "/moa <question> [--advisors a,b]", True),
        ("/usage", CommandCategory.CORE, "Shows token budgets and where live usage lives", "/usage", False),
        ("/compress", CommandCategory.CONTEXT, "Compacts context by summarizing older turns", "/compress", False),
        # 12. Model / Reasoning Commands
        ("/model", CommandCategory.MODEL, "Shows or changes active model", "/model [name]", True),
        ("/model list", CommandCategory.MODEL, "Lists available models", "/model list", False),
        ("/model auto", CommandCategory.MODEL, "Lets runtime choose best model", "/model auto", True),
        ("/model best", CommandCategory.MODEL, "Selects highest-capability model available", "/model best", False),
        ("/model cheap", CommandCategory.MODEL, "Selects cheapest suitable model", "/model cheap", False),
        ("/model fast", CommandCategory.MODEL, "Selects low-latency model", "/model fast", False),
        ("/model local", CommandCategory.MODEL, "Forces local model", "/model local", False),
        ("/model vision", CommandCategory.MODEL, "Selects vision-capable model", "/model vision", False),
        ("/model coding", CommandCategory.MODEL, "Selects coding-optimized model", "/model coding", False),
        ("/model research", CommandCategory.MODEL, "Selects research/reasoning model", "/model research", False),
        ("/model fallback", CommandCategory.MODEL, "Shows/configures fallback chain", "/model fallback", False),
        ("/model benchmark", CommandCategory.MODEL, "Benchmarks available models on task", "/model benchmark", True),
        ("/model route", CommandCategory.MODEL, "Shows why model was selected", "/model route", False),
        ("/model compare", CommandCategory.MODEL, "Compares models on same task", "/model compare", False),
        ("/reasoning", CommandCategory.MODEL, "Shows or changes reasoning effort", "/reasoning [auto|low|high|max]", True),
        ("/reasoning auto", CommandCategory.MODEL, "Dynamically selects reasoning effort", "/reasoning auto", False),
        ("/reasoning low", CommandCategory.MODEL, "Low reasoning for simple tasks", "/reasoning low", False),
        ("/reasoning high", CommandCategory.MODEL, "High reasoning for complex tasks", "/reasoning high", False),
        ("/reasoning max", CommandCategory.MODEL, "Maximum reasoning within budget", "/reasoning max", False),
        # 13. Tools & MCP Commands
        ("/tools search", CommandCategory.TOOLS, "Finds tools matching a task", "/tools search <query>", False),
        ("/tools inspect", CommandCategory.TOOLS, "Shows schema, permissions and capabilities", "/tools inspect <name>", False),
        ("/tools enable", CommandCategory.TOOLS, "Enables a tool", "/tools enable <name>", False),
        ("/tools disable", CommandCategory.TOOLS, "Disables a tool", "/tools disable <name>", False),
        ("/tools test", CommandCategory.TOOLS, "Tests a tool", "/tools test <name>", False),
        ("/mcp", CommandCategory.TOOLS, "Shows MCP subsystem status", "/mcp", True),
        ("/mcp list", CommandCategory.TOOLS, "Lists MCP servers", "/mcp list", False),
        ("/mcp add", CommandCategory.TOOLS, "Adds an MCP server", "/mcp add <server>", False),
        ("/mcp remove", CommandCategory.TOOLS, "Removes an MCP server", "/mcp remove <server>", False),
        ("/mcp enable", CommandCategory.TOOLS, "Enables an MCP server", "/mcp enable <server>", False),
        ("/mcp disable", CommandCategory.TOOLS, "Disables an MCP server", "/mcp disable <server>", False),
        ("/mcp inspect", CommandCategory.TOOLS, "Inspects MCP server/tools/resources", "/mcp inspect <server>", False),
        ("/mcp reload", CommandCategory.TOOLS, "Reloads MCP configuration and tools", "/mcp reload", True),
        ("/mcp auth", CommandCategory.TOOLS, "Handles MCP authorization", "/mcp auth <server>", False),
        ("/mcp health", CommandCategory.TOOLS, "Tests MCP server health", "/mcp health", False),
        # 14. Verification Commands
        ("/verify", CommandCategory.VERIFICATION, "Verifies current result against requirements", "/verify", True),
        ("/verify deep", CommandCategory.VERIFICATION, "Performs multi-layer verification", "/verify deep", True),
        ("/verify tests", CommandCategory.VERIFICATION, "Runs automated tests", "/verify tests", False),
        ("/verify security", CommandCategory.VERIFICATION, "Performs security validation", "/verify security", False),
        ("/verify evidence", CommandCategory.VERIFICATION, "Checks claims against evidence", "/verify evidence", False),
        ("/verify sources", CommandCategory.VERIFICATION, "Validates research sources/citations", "/verify sources", False),
        ("/verify artifact", CommandCategory.VERIFICATION, "Validates generated artifacts", "/verify artifact", False),
        ("/verify requirements", CommandCategory.VERIFICATION, "Checks every requirement against deliverable", "/verify requirements", True),
        ("/verify regression", CommandCategory.VERIFICATION, "Runs regression suite", "/verify regression", False),
        ("/verify visual", CommandCategory.VERIFICATION, "Performs screenshot/UI verification", "/verify visual", False),
        ("/verify runtime", CommandCategory.VERIFICATION, "Tests actual running application", "/verify runtime", False),
        ("/verify independent", CommandCategory.VERIFICATION, "Uses separate agent/model to verify result", "/verify independent", True),
        ("/verify adversarial", CommandCategory.VERIFICATION, "Attempts to break result", "/verify adversarial", True),
        ("/verify completeness", CommandCategory.VERIFICATION, "Finds missing pieces", "/verify completeness", False),
        ("/verify final", CommandCategory.VERIFICATION, "Performs complete final verification gate", "/verify final", True),
        # 15. Evidence Commands
        ("/evidence", CommandCategory.EVIDENCE, "Shows evidence collected for mission", "/evidence", True),
        ("/evidence add", CommandCategory.EVIDENCE, "Adds evidence manually or programmatically", "/evidence add <claim>", False),
        ("/evidence search", CommandCategory.EVIDENCE, "Finds evidence supporting a claim", "/evidence search <query>", False),
        ("/evidence graph", CommandCategory.EVIDENCE, "Displays claim -> evidence -> source relationships", "/evidence graph", True),
        ("/evidence verify", CommandCategory.EVIDENCE, "Checks evidence validity", "/evidence verify", False),
        ("/evidence conflicts", CommandCategory.EVIDENCE, "Finds contradictory evidence", "/evidence conflicts", False),
        ("/evidence confidence", CommandCategory.EVIDENCE, "Calculates confidence for claims", "/evidence confidence", False),
        ("/evidence gaps", CommandCategory.EVIDENCE, "Finds unsupported claims", "/evidence gaps", False),
        ("/evidence export", CommandCategory.EVIDENCE, "Exports evidence matrix", "/evidence export", False),
        # 16. Git & Coding Commands
        ("/code", CommandCategory.CODING, "Switches into coding-oriented execution mode", "/code [task]", False),
        ("/review", CommandCategory.CODING, "Independently reviews current implementation", "/review", True),
        ("/review security", CommandCategory.CODING, "Performs security-focused review", "/review security", False),
        ("/review architecture", CommandCategory.CODING, "Reviews architectural quality", "/review architecture", False),
        ("/review diff", CommandCategory.CODING, "Reviews current Git diff", "/review diff", False),
        ("/explain-changes", CommandCategory.CODING, "Explains current code changes", "/explain-changes", False),
        ("/test", CommandCategory.CODING, "Runs relevant test suites", "/test [pattern]", True),
        ("/fix", CommandCategory.CODING, "Investigates and fixes detected problems", "/fix", False),
        ("/debug", CommandCategory.CODING, "Starts structured debugging", "/debug", True),
        ("/refactor", CommandCategory.CODING, "Plans and executes a refactoring", "/refactor <scope>", False),
        ("/implement", CommandCategory.CODING, "Implements approved plan", "/implement", False),
        ("/patch", CommandCategory.CODING, "Generates/applies targeted patch", "/patch", False),
        ("/commit", CommandCategory.CODING, "Creates Git commit after verification", "/commit [msg]", False),
        ("/branch", CommandCategory.CODING, "Creates/manages work branch", "/branch [name]", False),
        ("/worktree", CommandCategory.CODING, "Creates isolated Git worktree for agent", "/worktree [name]", True),
        ("/diff", CommandCategory.CODING, "Shows current changes", "/diff", False),
        ("/rollback", CommandCategory.CODING, "Restores checkpoint or Git state", "/rollback", True),
        ("/changelog", CommandCategory.CODING, "Generates change summary", "/changelog", False),
        ("/pr", CommandCategory.CODING, "Creates or prepares a pull request", "/pr", False),
        ("/merge", CommandCategory.CODING, "Merges an approved change", "/merge", False),
        ("/release", CommandCategory.CODING, "Prepares release artifacts and checks", "/release", False),
        # 17. Browser & Computer Commands
        ("/browser", CommandCategory.BROWSER, "Shows browser status/capabilities", "/browser", False),
        ("/browser open", CommandCategory.BROWSER, "Opens a web page", "/browser open <url>", False),
        ("/browser search", CommandCategory.BROWSER, "Searches the web", "/browser search <query>", False),
        ("/browser inspect", CommandCategory.BROWSER, "Inspects DOM/accessibility structure", "/browser inspect", False),
        ("/browser screenshot", CommandCategory.BROWSER, "Captures visual state", "/browser screenshot", False),
        ("/browser click", CommandCategory.BROWSER, "Performs browser interaction", "/browser click <selector>", False),
        ("/browser fill", CommandCategory.BROWSER, "Fills forms", "/browser fill <selector> <value>", False),
        ("/browser extract", CommandCategory.BROWSER, "Extracts structured information", "/browser extract", False),
        ("/browser tabs", CommandCategory.BROWSER, "Shows active tabs", "/browser tabs", False),
        ("/browser network", CommandCategory.BROWSER, "Inspects network activity", "/browser network", False),
        ("/browser verify", CommandCategory.BROWSER, "Tests a website workflow", "/browser verify", False),
        ("/computer", CommandCategory.BROWSER, "Shows computer-use status", "/computer", False),
        ("/computer inspect", CommandCategory.BROWSER, "Inspects current screen/application", "/computer inspect", False),
        ("/computer act", CommandCategory.BROWSER, "Performs computer interaction", "/computer act <action>", False),
        ("/computer screenshot", CommandCategory.BROWSER, "Captures current desktop", "/computer screenshot", False),
        ("/computer verify", CommandCategory.BROWSER, "Verifies desktop action result", "/computer verify", False),
        # 18. RSI / Learning Commands
        ("/learn", CommandCategory.RSI, "Extracts reusable knowledge from current task", "/learn", True),
        ("/learn trajectory", CommandCategory.RSI, "Learns from complete execution trajectory", "/learn trajectory", False),
        ("/learn failure", CommandCategory.RSI, "Converts failure into reusable knowledge", "/learn failure", False),
        ("/experience", CommandCategory.RSI, "Searches previous task experiences", "/experience <query>", False),
        ("/experience similar", CommandCategory.RSI, "Finds similar successful trajectories", "/experience similar", False),
        ("/failure", CommandCategory.RSI, "Shows historical failures", "/failure", False),
        ("/failure analyze", CommandCategory.RSI, "Performs root-cause analysis on failures", "/failure analyze", True),
        ("/improve", CommandCategory.RSI, "Generates improvement proposal", "/improve", True),
        ("/improve agent", CommandCategory.RSI, "Improves agent configuration", "/improve agent <id>", False),
        ("/improve skill", CommandCategory.RSI, "Improves a skill", "/improve skill <name>", False),
        ("/improve workflow", CommandCategory.RSI, "Improves a workflow", "/improve workflow <name>", False),
        ("/improve planner", CommandCategory.RSI, "Evaluates and improves planning strategies", "/improve planner", False),
        ("/improve routing", CommandCategory.RSI, "Improves model and tool routing", "/improve routing", False),
        ("/improve memory", CommandCategory.RSI, "Improves memory retrieval/compression strategy", "/improve memory", False),
        ("/evolve", CommandCategory.RSI, "Starts evolutionary optimization", "/evolve", True, True),
        ("/evolve candidate", CommandCategory.RSI, "Creates improvement candidate", "/evolve candidate", False),
        ("/evolve benchmark", CommandCategory.RSI, "Benchmarks candidate improvements", "/evolve benchmark", True),
        ("/evolve compete", CommandCategory.RSI, "Runs competing candidate strategies", "/evolve compete", False),
        ("/evolve promote", CommandCategory.RSI, "Promotes verified candidate", "/evolve promote", True),
        ("/evolve rollback", CommandCategory.RSI, "Reverts unsuccessful evolution", "/evolve rollback", False),
        # 19. AVO / Evolution Commands
        ("/avo", CommandCategory.EVOLUTION, "Opens Agentic Variation Optimization control", "/avo", True),
        ("/avo start", CommandCategory.EVOLUTION, "Starts candidate generation and evaluation", "/avo start", False),
        ("/avo stop", CommandCategory.EVOLUTION, "Stops evolution run", "/avo stop", False),
        ("/avo status", CommandCategory.EVOLUTION, "Shows current candidates and fitness", "/avo status", False),
        ("/avo candidates", CommandCategory.EVOLUTION, "Lists candidate strategies and agents", "/avo candidates", False),
        ("/avo generate", CommandCategory.EVOLUTION, "Generates alternative candidates", "/avo generate", False),
        ("/avo mutate", CommandCategory.EVOLUTION, "Mutates agent/strategy/topology", "/avo mutate", True),
        ("/avo evaluate", CommandCategory.EVOLUTION, "Evaluates candidate performance", "/avo evaluate", False),
        ("/avo compare", CommandCategory.EVOLUTION, "Compares candidate fitness", "/avo compare", False),
        ("/avo lineage", CommandCategory.EVOLUTION, "Shows candidate ancestry and mutations", "/avo lineage", True),
        ("/avo benchmark", CommandCategory.EVOLUTION, "Runs candidate benchmarks", "/avo benchmark", False),
        ("/avo adversarial", CommandCategory.EVOLUTION, "Runs adversarial testing", "/avo adversarial", False),
        ("/avo shadow", CommandCategory.EVOLUTION, "Runs candidate in shadow mode", "/avo shadow", False),
        ("/avo canary", CommandCategory.EVOLUTION, "Deploys candidate gradually", "/avo canary", False),
        ("/avo promote", CommandCategory.EVOLUTION, "Promotes winning candidate", "/avo promote", False),
        ("/avo rollback", CommandCategory.EVOLUTION, "Rolls back evolved candidate", "/avo rollback", False),
        ("/avo archive", CommandCategory.EVOLUTION, "Archives candidate history", "/avo archive", False),
        # 20. Autonomous Operations Commands
        ("/cron", CommandCategory.AUTONOMOUS_OPS, "Manage scheduled autonomous jobs", "/cron", True),
        ("/cron create", CommandCategory.AUTONOMOUS_OPS, "Creates scheduled mission", "/cron create <schedule> <task>", False),
        ("/cron list", CommandCategory.AUTONOMOUS_OPS, "Lists scheduled missions", "/cron list", False),
        ("/cron pause", CommandCategory.AUTONOMOUS_OPS, "Pauses scheduled mission", "/cron pause <id>", False),
        ("/cron resume", CommandCategory.AUTONOMOUS_OPS, "Resumes scheduled execution", "/cron resume <id>", False),
        ("/cron remove", CommandCategory.AUTONOMOUS_OPS, "Removes scheduled job", "/cron remove <id>", False),
        ("/cron run", CommandCategory.AUTONOMOUS_OPS, "Immediately executes scheduled job", "/cron run <id>", False),
        ("/monitor", CommandCategory.AUTONOMOUS_OPS, "Creates monitoring agent or job", "/monitor <target>", True),
        ("/monitor status", CommandCategory.AUTONOMOUS_OPS, "Shows monitored systems", "/monitor status", False),
        ("/watch", CommandCategory.AUTONOMOUS_OPS, "Watches file/repo/service for changes", "/watch <path>", False),
        ("/watch stop", CommandCategory.AUTONOMOUS_OPS, "Stops a watcher", "/watch stop <id>", False),
        ("/trigger", CommandCategory.AUTONOMOUS_OPS, "Shows/creates event triggers", "/trigger", False),
        ("/workflow", CommandCategory.AUTONOMOUS_OPS, "Shows or manages reusable workflows", "/workflow", True),
        ("/workflow create", CommandCategory.AUTONOMOUS_OPS, "Converts successful trajectory into workflow", "/workflow create <name>", False),
        ("/workflow run", CommandCategory.AUTONOMOUS_OPS, "Runs a stored workflow", "/workflow run <name>", False),
        ("/workflow optimize", CommandCategory.AUTONOMOUS_OPS, "Improves workflow execution", "/workflow optimize <name>", False),
        # 21. Security Commands
        ("/security", CommandCategory.SECURITY, "Shows security status and active policies", "/security", True),
        ("/security audit", CommandCategory.SECURITY, "Performs security audit", "/security audit", True),
        ("/security scan", CommandCategory.SECURITY, "Scans files/tools/dependencies for risks", "/security scan", False),
        ("/security permissions", CommandCategory.SECURITY, "Shows current permissions", "/security permissions", False),
        ("/security revoke", CommandCategory.SECURITY, "Revokes agent capability", "/security revoke <cap>", False),
        ("/security credentials", CommandCategory.SECURITY, "Shows credential-broker status without secrets", "/security credentials", False),
        ("/security sandbox", CommandCategory.SECURITY, "Shows sandbox configuration", "/security sandbox", False),
        ("/security policy", CommandCategory.SECURITY, "Displays active policy rules", "/security policy", False),
        ("/security redteam", CommandCategory.SECURITY, "Runs adversarial security testing", "/security redteam", True),
        ("/security inject", CommandCategory.SECURITY, "Tests prompt-injection defenses", "/security inject", False),
        ("/security secrets", CommandCategory.SECURITY, "Detects accidental secret exposure", "/security secrets", False),
        ("/security lockdown", CommandCategory.SECURITY, "Immediately restricts dangerous capabilities", "/security lockdown", True, False, True),
        ("/security approve", CommandCategory.SECURITY, "Approves pending privileged action", "/security approve <id>", False),
        ("/security deny", CommandCategory.SECURITY, "Denies privileged action", "/security deny <id>", False),
        # 22. Runtime & System Commands
        ("/runtime", CommandCategory.RUNTIME, "Shows runtime configuration", "/runtime", False),
        ("/runtime inspect", CommandCategory.RUNTIME, "Displays active runtime components", "/runtime inspect", False),
        ("/runtime reload", CommandCategory.RUNTIME, "Reloads runtime configuration", "/runtime reload", False),
        ("/runtime restart", CommandCategory.RUNTIME, "Restarts agent runtime safely", "/runtime restart", False),
        ("/runtime shutdown", CommandCategory.RUNTIME, "Gracefully shuts down all agents", "/runtime shutdown", False),
        ("/runtime health", CommandCategory.RUNTIME, "Checks runtime health", "/runtime health", False),
        ("/runtime resources", CommandCategory.RUNTIME, "Shows CPU/RAM/GPU/disk usage", "/runtime resources", False),
        ("/runtime processes", CommandCategory.RUNTIME, "Lists agent processes", "/runtime processes", False),
        ("/runtime workers", CommandCategory.RUNTIME, "Shows active workers", "/runtime workers", False),
        ("/runtime queues", CommandCategory.RUNTIME, "Shows queued tasks", "/runtime queues", False),
        ("/runtime events", CommandCategory.RUNTIME, "Shows event-bus activity", "/runtime events", False),
        ("/runtime logs", CommandCategory.RUNTIME, "Shows runtime logs", "/runtime logs", False),
        # 23. Observability Commands
        ("/trace", CommandCategory.OBSERVABILITY, "Shows execution trace for current mission", "/trace", True),
        ("/trace agent", CommandCategory.OBSERVABILITY, "Shows one agent trajectory", "/trace agent <id>", False),
        ("/trace task", CommandCategory.OBSERVABILITY, "Shows one task execution history", "/trace task <id>", False),
        ("/trace tools", CommandCategory.OBSERVABILITY, "Shows tool-call trajectory", "/trace tools", False),
        ("/trace errors", CommandCategory.OBSERVABILITY, "Shows failures in execution path", "/trace errors", False),
        ("/metrics", CommandCategory.OBSERVABILITY, "Shows system performance metrics", "/metrics", False),
        ("/cost", CommandCategory.OBSERVABILITY, "Shows token/API/infrastructure costs", "/cost", True),
        ("/usage", CommandCategory.OBSERVABILITY, "Shows model and tool usage", "/usage", False),
        ("/latency", CommandCategory.OBSERVABILITY, "Shows latency by model/tool/agent", "/latency", False),
        ("/performance", CommandCategory.OBSERVABILITY, "Shows agent/system performance", "/performance", False),
        ("/telemetry", CommandCategory.OBSERVABILITY, "Shows telemetry configuration", "/telemetry", False),
        ("/flightrecorder", CommandCategory.OBSERVABILITY, "Retrieves complete execution history", "/flightrecorder", True),
        # 24. Session Commands
        ("/new", CommandCategory.SESSION, "Starts clean session", "/new", True),
        ("/reset", CommandCategory.SESSION, "Resets current session", "/reset", False),
        ("/resume", CommandCategory.SESSION, "Resumes previous session", "/resume [id]", True),
        ("/sessions", CommandCategory.SESSION, "Lists previous sessions", "/sessions", False),
        ("/session", CommandCategory.SESSION, "Shows current session details", "/session", False),
        ("/session search", CommandCategory.SESSION, "Searches historical sessions", "/session search <query>", False),
        ("/session fork", CommandCategory.SESSION, "Creates new session from current state", "/session fork", False),
        ("/session clone", CommandCategory.SESSION, "Clones session state", "/session clone", False),
        ("/save", CommandCategory.SESSION, "Saves session state", "/save", False),
        ("/title", CommandCategory.SESSION, "Sets session title", "/title <title>", False),
        ("/history", CommandCategory.SESSION, "Shows conversation history", "/history", False),
        ("/retry", CommandCategory.SESSION, "Retries last request", "/retry", False),
        ("/undo", CommandCategory.SESSION, "Removes last interaction", "/undo", False),
        ("/clear", CommandCategory.SESSION, "Clears current conversation context", "/clear", False),
        ("/compact", CommandCategory.SESSION, "Compresses context", "/compact", False),
        ("/newtask", CommandCategory.SESSION, "Creates new task with distilled context", "/newtask <task>", True),
        ("/handoff", CommandCategory.SESSION, "Hands current work to another agent/session", "/handoff <agent>", True),
        # 25. Human Collaboration Commands
        ("/ask", CommandCategory.COLLABORATION, "Ask human for missing information", "/ask <question>", False),
        ("/approve", CommandCategory.COLLABORATION, "Approve pending operation", "/approve [id]", True),
        ("/deny", CommandCategory.COLLABORATION, "Reject pending operation", "/deny [id]", True),
        ("/pause", CommandCategory.COLLABORATION, "Pause execution for human intervention", "/pause", False),
        ("/resume-hitl", CommandCategory.COLLABORATION, "Continue after intervention", "/resume-hitl", False),
        ("/clarify", CommandCategory.COLLABORATION, "Ask user to clarify mission requirements", "/clarify <topic>", False),
        ("/feedback", CommandCategory.COLLABORATION, "Give feedback on current result", "/feedback <text>", False),
        ("/rate", CommandCategory.COLLABORATION, "Rate output quality", "/rate <1-5>", False),
        ("/correct", CommandCategory.COLLABORATION, "Correct an agent assumption", "/correct <assumption>", False),
        ("/steer", CommandCategory.COLLABORATION, "Change direction without destroying current state", "/steer <instruction>", True),
        ("/interrupt", CommandCategory.COLLABORATION, "Interrupt current reasoning/execution", "/interrupt", False),
        # 26. Agent Communication Commands
        ("/msg", CommandCategory.COMMUNICATION, "Sends direct message to agent", "/msg <agent> <content>", False),
        ("/broadcast", CommandCategory.COMMUNICATION, "Sends information to all swarm agents", "/broadcast <content>", False),
        ("/ask-agent", CommandCategory.COMMUNICATION, "Queries another agent", "/ask-agent <agent> <question>", False),
        ("/delegate", CommandCategory.COMMUNICATION, "Gives work to another agent", "/delegate <agent> <task>", True),
        ("/consult", CommandCategory.COMMUNICATION, "Requests specialist advice without transferring ownership", "/consult <specialist> <query>", False),
        ("/negotiate", CommandCategory.COMMUNICATION, "Allows agents to negotiate task ownership", "/negotiate <task>", False),
        ("/vote", CommandCategory.COMMUNICATION, "Requests distributed agent voting", "/vote <topic>", False),
        ("/consensus", CommandCategory.COMMUNICATION, "Runs evidence-based consensus procedure", "/consensus <proposal>", False),
        ("/debate", CommandCategory.COMMUNICATION, "Starts structured multi-agent debate", "/debate <motion>", True),
        ("/judge", CommandCategory.COMMUNICATION, "Runs independent judge over competing answers", "/judge <question>", False),
        # 27. Artifact Commands
        ("/artifact", CommandCategory.ARTIFACT, "Shows generated artifacts", "/artifact", True),
        ("/artifact list", CommandCategory.ARTIFACT, "Lists mission artifacts", "/artifact list", False),
        ("/artifact inspect", CommandCategory.ARTIFACT, "Shows artifact metadata and provenance", "/artifact inspect <name>", False),
        ("/artifact diff", CommandCategory.ARTIFACT, "Compares artifact versions", "/artifact diff <v1> <v2>", False),
        ("/artifact lineage", CommandCategory.ARTIFACT, "Shows artifact ancestry and provenance", "/artifact lineage <name>", True),
        ("/artifact verify", CommandCategory.ARTIFACT, "Verifies artifact integrity", "/artifact verify <name>", False),
        ("/artifact export", CommandCategory.ARTIFACT, "Exports an artifact", "/artifact export <name>", False),
        ("/artifact restore", CommandCategory.ARTIFACT, "Restores previous artifact version", "/artifact restore <name>", False),
        ("/artifact promote", CommandCategory.ARTIFACT, "Marks artifact as approved output", "/artifact promote <name>", False),
        ("/artifact archive", CommandCategory.ARTIFACT, "Archives old artifacts", "/artifact archive <name>", False),
        # 28. World Model Commands
        ("/world", CommandCategory.WORLD_MODEL, "Shows agent world model", "/world", True),
        ("/world inspect", CommandCategory.WORLD_MODEL, "Inspects known entities and state", "/world inspect", False),
        ("/world refresh", CommandCategory.WORLD_MODEL, "Re-observes environment", "/world refresh", False),
        ("/world changes", CommandCategory.WORLD_MODEL, "Shows changes since last observation", "/world changes", False),
        ("/knowledge", CommandCategory.WORLD_MODEL, "Shows knowledge base status", "/knowledge", False),
        ("/knowledge search", CommandCategory.WORLD_MODEL, "Searches semantic knowledge", "/knowledge search <query>", False),
        ("/knowledge graph", CommandCategory.WORLD_MODEL, "Displays knowledge graph relationships", "/knowledge graph", False),
        ("/knowledge update", CommandCategory.WORLD_MODEL, "Updates knowledge from verified evidence", "/knowledge update", False),
        ("/state", CommandCategory.WORLD_MODEL, "Shows current task/world state", "/state", True),
        ("/state diff", CommandCategory.WORLD_MODEL, "Shows state changes", "/state diff", False),
        ("/state checkpoint", CommandCategory.WORLD_MODEL, "Saves current state", "/state checkpoint", False),
        ("/state restore", CommandCategory.WORLD_MODEL, "Restores state checkpoint", "/state restore", False),
    ]
    return entries
