"""Typed Observation event definitions for OpenHands-style EventStream architecture."""

from __future__ import annotations

import time
import uuid
from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any


class ObservationType(str, Enum):
    CMD_OUTPUT = "cmd_output"
    FILE_EDIT_RESULT = "file_edit_result"
    CRITIC_VERDICT = "critic_verdict"
    ERROR = "error"
    GENERIC = "generic"


@dataclass
class Observation:
    """Base class for all environment/system observations."""
    observation_type: ObservationType
    action_id: str | None = None
    content: str = ""
    observation_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: float = field(default_factory=time.time)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["observation_type"] = self.observation_type.value
        return data


@dataclass
class CmdOutputObservation(Observation):
    """Output generated by a shell command execution."""
    exit_code: int = 0
    stdout: str = ""
    stderr: str = ""
    duration_ms: float = 0.0

    def __init__(
        self,
        exit_code: int = 0,
        stdout: str = "",
        stderr: str = "",
        duration_ms: float = 0.0,
        action_id: str | None = None,
        **kwargs: Any,
    ):
        content = stdout if exit_code == 0 else f"{stdout}\n[STDERR]: {stderr}".strip()
        super().__init__(
            observation_type=ObservationType.CMD_OUTPUT,
            action_id=action_id,
            content=content,
            **kwargs,
        )
        self.exit_code = exit_code
        self.stdout = stdout
        self.stderr = stderr
        self.duration_ms = duration_ms


@dataclass
class FileEditObservation(Observation):
    """Result of a file creation, replacement, or modification."""
    path: str = ""
    success: bool = True
    diff: str | None = None
    lines_added: int = 0
    lines_removed: int = 0

    def __init__(
        self,
        path: str,
        success: bool = True,
        diff: str | None = None,
        lines_added: int = 0,
        lines_removed: int = 0,
        action_id: str | None = None,
        **kwargs: Any,
    ):
        content = f"File '{path}' edited successfully (+{lines_added}, -{lines_removed})" if success else f"Failed to edit file '{path}'"
        super().__init__(
            observation_type=ObservationType.FILE_EDIT_RESULT,
            action_id=action_id,
            content=content,
            **kwargs,
        )
        self.path = path
        self.success = success
        self.diff = diff
        self.lines_added = lines_added
        self.lines_removed = lines_removed


@dataclass
class CriticObservation(Observation):
    """Observation emitted by a completion or safety critic."""
    critic_name: str = ""
    verdict: str = "approved"
    reason: str = ""
    diagnostic_prompt: str | None = None

    def __init__(
        self,
        critic_name: str,
        verdict: str,
        reason: str,
        diagnostic_prompt: str | None = None,
        action_id: str | None = None,
        **kwargs: Any,
    ):
        super().__init__(
            observation_type=ObservationType.CRITIC_VERDICT,
            action_id=action_id,
            content=f"[{critic_name}] {verdict.upper()}: {reason}",
            **kwargs,
        )
        self.critic_name = critic_name
        self.verdict = verdict
        self.reason = reason
        self.diagnostic_prompt = diagnostic_prompt


@dataclass
class ErrorObservation(Observation):
    """Observation capturing an exception or fatal execution failure."""
    error_type: str = "ExecutionError"
    message: str = ""
    traceback_str: str | None = None

    def __init__(
        self,
        error_type: str,
        message: str,
        traceback_str: str | None = None,
        action_id: str | None = None,
        **kwargs: Any,
    ):
        super().__init__(
            observation_type=ObservationType.ERROR,
            action_id=action_id,
            content=f"{error_type}: {message}",
            **kwargs,
        )
        self.error_type = error_type
        self.message = message
        self.traceback_str = traceback_str
