"""ReproductionSynthesizer: Generates standalone executable reproduction test scripts."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from deerflow.reproduction.models import ReproductionScript

logger = logging.getLogger(__name__)


class ReproductionSynthesizer:
    """Synthesizes isolated Python reproduction scripts with strict exit-code semantics."""

    def synthesize(
        self,
        issue_description: str,
        test_body: str,
        target_module: Optional[str] = None,
        script_name: str = "reproduce_issue.py",
    ) -> ReproductionScript:
        """Create a standalone reproduction script string with deterministic exit codes."""
        template = f'''"""Standalone Autonomous Bug Reproduction Script.
Generated by DeerFlow Autonomous Reproduction Engine.
Issue: {issue_description.strip()}
"""

import sys
import traceback

def reproduce():
    # --- Autonomous Reproduction Logic Begin ---
{self._indent(test_body.strip(), 4)}
    # --- Autonomous Reproduction Logic End ---

if __name__ == "__main__":
    try:
        reproduce()
        print("REPRODUCTION_PASSED: Verification succeeded; no bug detected.")
        sys.exit(0)
    except AssertionError as e:
        print(f"REPRODUCED_BUG (AssertionError): {{e}}", file=sys.stderr)
        traceback.print_exc()
        sys.exit(1)
    except Exception as e:
        print(f"REPRODUCED_BUG (Exception): {{type(e).__name__}}: {{e}}", file=sys.stderr)
        traceback.print_exc()
        sys.exit(1)
'''
        return ReproductionScript(
            code=template,
            script_name=script_name,
            target_module=target_module,
            description=issue_description,
        )

    def write_script(self, script: ReproductionScript, target_dir: Path) -> Path:
        """Save the synthesized reproduction script into target directory."""
        target_dir.mkdir(parents=True, exist_ok=True)
        script_path = target_dir / script.script_name
        script_path.write_text(script.code, encoding="utf-8")
        return script_path

    def _indent(self, text: str, spaces: int) -> str:
        prefix = " " * spaces
        return "\n".join(prefix + line if line.strip() else line for line in text.splitlines())
